@startuml
left to right direction

actor pompiste
actor client
rectangle "PetroShawi" {
    usecase "Prend essence" as UC1
    usecase "Enregistrer paiement" as UC2
    
}

pompiste--> UC2
client --> UC1
pompiste--|>client

@enduml